import express from 'express';
import { evaluateDesignPlan } from '../domain/designPlan.js';

export default function governedDesigns({ pool, authenticate }) {
  const router=express.Router();
  const providers=new Set(['cad','bim','gis','cost-catalog','product-catalog','render-worker','contractor','object-storage','permitting']);
  const ctx=req=>{const actor=String(req.user?.id||req.user?.sub||'');return{actor,tenant:String(req.user?.tenantId||req.user?.tenant_id||`user:${actor}`),role:req.user?.role||'designer'}};
  const idem=req=>{const key=req.get('Idempotency-Key');return key&&key.length<=128?key:null};
  const audit=(client,x,id,type,details={})=>client.query('INSERT INTO governed_case_events(tenant_id,case_id,actor_id,event_type,details) VALUES($1,$2,$3,$4,$5)',[x.tenant,id,x.actor,type,details]);
  router.use(authenticate);
  router.post('/integrations/:outboxId/result',async(req,res,next)=>{try{const x=ctx(req);if(!['integration_worker','admin'].includes(x.role))return res.status(403).json({error:'integration worker role required'});if(!['delivered','failed'].includes(req.body.status))return res.status(422).json({error:'invalid result status'});const r=await pool.query(`UPDATE integration_outbox SET status=CASE WHEN $1='delivered' THEN 'delivered' WHEN attempts+1>=5 THEN 'dead_letter' ELSE 'failed' END,attempts=attempts+1,last_error=CASE WHEN $1='failed' THEN $2 ELSE NULL END,next_attempt_at=NOW()+(INTERVAL '1 minute'*LEAST(60,POWER(2,attempts))),updated_at=NOW() WHERE id=$3 AND tenant_id=$4 AND status IN ('queued','processing','failed') RETURNING *`,[req.body.status,String(req.body.error||'').slice(0,1000),req.params.outboxId,x.tenant]);if(!r.rowCount)return res.status(409).json({error:'missing or terminal outbox item'});res.json(r.rows[0])}catch(error){next(error)}});
  router.get('/',async(req,res,next)=>{try{const x=ctx(req),r=await pool.query("SELECT * FROM governed_cases WHERE tenant_id=$1 AND workflow_type='floor-plan-design' ORDER BY updated_at DESC LIMIT 100",[x.tenant]);res.json(r.rows)}catch(error){next(error)}});
  router.post('/',async(req,res,next)=>{const x=ctx(req),key=idem(req),evaluation=evaluateDesignPlan(req.body.input);if(!key)return res.status(400).json({error:'Idempotency-Key required'});if(evaluation.errors.length)return res.status(422).json(evaluation);if(!Array.isArray(req.body.provenance)||!req.body.provenance.length)return res.status(422).json({error:'asset and requirement provenance required'});const client=await pool.connect();try{await client.query('BEGIN');const r=await client.query(`INSERT INTO governed_cases(tenant_id,workflow_type,input,result,assumptions,uncertainty,provenance,created_by,idempotency_key) VALUES($1,'floor-plan-design',$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(tenant_id,idempotency_key) DO UPDATE SET updated_at=governed_cases.updated_at RETURNING *`,[x.tenant,req.body.input,evaluation.result,evaluation.assumptions,evaluation.uncertainty,req.body.provenance,x.actor,key]);await audit(client,x,r.rows[0].id,'evaluated',{idempotencyKey:key});await client.query('COMMIT');res.status(201).json(r.rows[0])}catch(error){await client.query('ROLLBACK');next(error)}finally{client.release()}});
  router.post('/:id/submit',async(req,res,next)=>{try{const x=ctx(req),r=await pool.query("UPDATE governed_cases SET status='submitted',version=version+1,updated_at=NOW() WHERE id=$1 AND tenant_id=$2 AND status='draft' AND version=$3 RETURNING *",[req.params.id,x.tenant,Number(req.body.version)]);if(!r.rowCount)return res.status(409).json({error:'missing, stale, or not draft'});await audit(pool,x,req.params.id,'submitted');res.json(r.rows[0])}catch(error){next(error)}});
  router.post('/:id/decision',async(req,res,next)=>{try{const x=ctx(req);if(!['qualified_designer','contractor','admin'].includes(x.role))return res.status(403).json({error:'qualified designer/contractor approval role required'});if(!['approved','rejected'].includes(req.body.decision)||!String(req.body.note||'').trim())return res.status(422).json({error:'decision and note required'});const r=await pool.query("UPDATE governed_cases SET status=$1,approved_by=$2,approval_note=$3,version=version+1,updated_at=NOW() WHERE id=$4 AND tenant_id=$5 AND status='submitted' AND version=$6 AND created_by<>$2 RETURNING *",[req.body.decision,x.actor,req.body.note,req.params.id,x.tenant,Number(req.body.version)]);if(!r.rowCount)return res.status(409).json({error:'stale/not submitted, or independent approval failed'});await audit(pool,x,req.params.id,req.body.decision,{note:req.body.note});res.json(r.rows[0])}catch(error){next(error)}});
  router.post('/:id/integrations',async(req,res,next)=>{try{const x=ctx(req),key=idem(req);if(!key||!providers.has(req.body.provider))return res.status(422).json({error:'allowed provider and Idempotency-Key required'});const own=await pool.query("SELECT id FROM governed_cases WHERE id=$1 AND tenant_id=$2 AND status='approved'",[req.params.id,x.tenant]);if(!own.rowCount)return res.status(409).json({error:'approved design required'});const r=await pool.query(`INSERT INTO integration_outbox(tenant_id,case_id,provider,operation,payload,idempotency_key) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,provider,idempotency_key) DO UPDATE SET updated_at=integration_outbox.updated_at RETURNING *`,[x.tenant,req.params.id,req.body.provider,req.body.operation||'export',req.body.payload||{},key]);res.status(202).json(r.rows[0])}catch(error){next(error)}});
  return router;
}
